name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull
          echo "LFS files pulled successfully"
          
      - name: Verify LFS files are properly pulled
        run: |
          echo "Checking LFS file status..."
          git lfs ls-files
          echo "Sample file sizes:"
          find manuals -name "*.pdf" -type f -exec ls -lh {} \; | head -5
          echo "Checking if files are LFS pointers:"
          find manuals -name "*.pdf" -type f -exec head -1 {} \; | head -5
          echo "Verifying PDF file headers:"
          find manuals -name "*.pdf" -type f -exec file {} \; | head -5
            
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate sitemap
        run: |
          echo "Generating sitemap..."
          node generate-sitemap.js || (echo "Falling back to simple sitemap generator" && node simple-sitemap.js)
          
      - name: Create .nojekyll file
        run: touch .nojekyll
        
      - name: Create _headers file for Netlify-style headers (GitHub Pages alternative)
        run: |
          cat > _headers << 'EOF'
          /*
            Access-Control-Allow-Origin: *
            Access-Control-Allow-Methods: GET, POST, OPTIONS
            Access-Control-Allow-Headers: Content-Type
          
          /*.pdf
            Content-Type: application/pdf
            Content-Disposition: inline
          EOF

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
